### ISSUE TITLE
Not registering new portals

### ISSUE THREAD

**Issue by Wolfthing** [FLamparski/seeraccept#23] opened 2015-05-28 22:17 UTC
I've recently had a portal accepted but the Ipsum portal summary service doesn't seem to find the "congratulations your portal suggestion has been accepted".

Problem with some sort of text recognition maybe?

Cheers

**Comment by urbels** [comment] 2015-05-29 13:03
Ingress recently changed email replies.

**Comment by FLamparski** [comment] 2015-05-29 13:10
I am working on it. So far it's picking up new format submissions, but not
other events - I'll have to look into why that is the case (and perhaps
streamline the mail checking process a bit).

**Comment by Wolfthing** [comment] 2015-05-31 20:32
Not sure how this is closed - still not working. It shows that I've submitted 10 portals and none are live - but one of them most definitely is. Would you like to see the confirmation e-mail?

**Comment by FLamparski** [comment] 2015-05-31 20:41
After the patch I did this morning, Ipsum is picking up one new-style live
and one new-style rejection from my account. Unless there's a third format
I don't know about, it should work. For reference, I am using these regexes
on the new-style review emails (Gmail query `from:ingress-support@google.com
"Portal review complete"`):

* Live: `/Portal is now available on your Scanner/g`
* Rejected: `/we have decided not to accept this candidate/g`
* Duplicate: `/Your candidate is a duplicate of either an existing Portal/g`

If you have any doubts, please send through the relevant emails with
complete headers. If you'd prefer not to do it on the public internet,
please forward them to hello@filipwieland.com. Thanks!

**Comment by Wolfthing** [comment] 2015-06-01 17:40
I had another portal accepted this morning and it's not picking that one up either. I'll forward it on to your hello email address.

**Comment by FLamparski** [comment] 2015-06-02 08:46
So for some reason it's just not downloading the new "review complete" emails, or at least not all of them. I'm doing some major refactoring on the mail checking engine to simplify it in hopes that it will work better this way, but for some reason it's just not. I'll update the issue once I'm onto something. The new version is not deployed yet as some things are still partly broken.

**Comment by Wolfthing** [comment] 2015-06-02 09:49
Many thanks for persevering with it. I'm sure you'll crack it.

On a positive note, I'm loving the clean simple interface on an Android phone - looks great!

**Comment by FLamparski** [comment] 2015-06-02 20:33
As of 42c0ea0, Ipsum is using a different method of pulling in mail. The previous approach of spinning up multiple searches was too complicated, and the code was messy. I noticed that there was a race condition at the end of the result list between the result stream closing and the MIME parser finishing the last messages, and most of the time, the stream was winning. This should be fixed now, as I explicitly keep track of which messages have been fully parsed and only return the result when all of them have been. This should fix the issue. The new version of Ipsum has been deployed.

**Comment by Wolfthing** [comment] 2015-06-02 22:00
Wahoo! It works! Top job!

Many thanks.

This is case is now okay to be closed.

P.S - on the feature wishlist it'd be good to see photo, description and location updates too - no rush ;-)

**Comment by FLamparski** [comment] 2015-06-02 22:07
At the moment you get an Intel link on live portals. I did wonder if I
could geolocate from photos but alas they scrub the exif tags so no dice
here.

**Closed** 2015-06-03 13:12 UTC
